# Generated by Django 4.1.7 on 2023-04-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_items', '0002_alter_menuitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
